build:
  maxIssues: 100
  excludeCorrectable: false

complexity:
  LongMethod:
    threshold: 60
  LongParameterList:
    functionThreshold: 8
    constructorThreshold: 10
  TooManyFunctions:
    thresholdInFiles: 25
    thresholdInClasses: 25
    thresholdInInterfaces: 15
    thresholdInObjects: 15
    thresholdInEnums: 10

naming:
  FunctionNaming:
    functionPattern: '[a-z][a-zA-Z0-9]*'
  VariableNaming:
    variablePattern: '[a-z][a-zA-Z0-9]*'
  ClassNaming:
    classPattern: '[A-Z][a-zA-Z0-9]*'

style:
  MagicNumber:
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
      - '100'
      - '1000'
  MaxLineLength:
    maxLineLength: 120
  WildcardImport:
    active: false
  UnusedPrivateMember:
    allowedNames: '(_|ignored|expected|serialVersionUID)'
