build:
  maxIssues: 0
  excludeCorrectable: false

complexity:
  LongMethod:
    threshold: 120
  LongParameterList:
    functionThreshold: 12
    constructorThreshold: 15
  TooManyFunctions:
    thresholdInFiles: 30
    thresholdInClasses: 60
    thresholdInInterfaces: 30
    thresholdInObjects: 30
    thresholdInEnums: 10
  CyclomaticComplexMethod:
    threshold: 50
  NestedBlockDepth:
    threshold: 5
  LargeClass:
    threshold: 2000

naming:
  FunctionNaming:
    functionPattern: '[a-z][a-zA-Z0-9]*'
  VariableNaming:
    variablePattern: '[a-z][a-zA-Z0-9]*'
  ClassNaming:
    classPattern: '[A-Z][a-zA-Z0-9]*'

style:
  MagicNumber:
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
      - '3'
      - '4'
      - '5'
      - '6'
      - '7'
      - '8'
      - '10'
      - '14'
      - '20'
      - '24'
      - '30'
      - '60'
      - '100'
      - '1000'
    ignorePropertyDeclaration: true
    ignoreLocalVariableDeclaration: true
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: true
    ignoreHashCodeFunction: true
    ignoreEnums: true
    ignoreRanges: true
    ignoreExtensionFunctions: true
  MaxLineLength:
    maxLineLength: 140
  WildcardImport:
    active: false
  UnusedPrivateMember:
    allowedNames: '(_|ignored|expected|serialVersionUID)'
  ReturnCount:
    max: 10
  LoopWithTooManyJumpStatements:
    maxJumpCount: 3

exceptions:
  TooGenericExceptionCaught:
    active: false
